name: Run benchmarks
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.github/**'
      - 'LICENSE'
      - 'bench.bat'
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install LuaJIT
        run: sudo apt-get install -y luajit
      
      - name: Setup PyPy
        uses: actions/setup-python@v2
        with:
          python-version: pypy2

      - name: Run benchmarks
        run: node bench.js

      - name: Commit new results
        uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          message: 'chore: update results'
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
